# Enable debug logs.
debug: false


spring:
  application:
    name: 'KafkaManager'
  kafka:
    admin:
      client-id: 'kafkaManager'
    bootstrap-servers: 'localhost:9092'

zookeeper:
  url: 'localhost:2181'

management:
  endpoints:
    web:
      base-path: /internal/monitor
      exposure:
        include: '*'

logging:
  level:
    io:
      beco: debug
